(function(){
'use strict';
const KEY='laolao_meta_lab_v1', day=()=>new Date().toLocaleDateString('sv-SE'), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tools=[['focus','星轨冲刺','专注计时与记录'],['task','任务航线','优先级与截止日'],['card','记忆晶片','间隔复习卡片'],['exam','倒计时信标','考试与重要日期'],['review','复习雷达','今日到期的晶片'],['expense','能量补给','校园支出与预算'],['course','课程导航','课程时间与教室'],['diary','心情黑匣子','每日心情与记录'],['pack','校园装备','出门前检查清单'],['stats','时空回放','真实记录的周报']];
let state={items:[],logs:[],budget:0,timer:null}, active='focus', answer=false, host, tick;
try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&Array.isArray(x.items)&&Array.isArray(x.logs))state={...state,...x}}catch(e){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){feedback('设备存储失败，请先释放空间；当前记录未保存。');return false}}
const items=t=>state.items.filter(x=>x.type===t), dateAfter=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toLocaleDateString('sv-SE')}, diff=d=>Math.round((new Date(d+'T12:00:00')-new Date(day()+'T12:00:00'))/86400000);
function feedback(s){const e=host?.querySelector('.ml-feedback');if(e)e.textContent=s}
function record(kind,n=1){state.logs.push({day:day(),kind,n});save()}
function fields(list){return list.map(([name,label,type='text',value=''])=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" required ${type==='text'?'maxlength="300"':''} ${type==='number'?'min="0.01" step="0.01"':''}></label>`).join('')}
function form(t,list){return `<form class="ml-form" data-form="${t}">${fields(list)}<button>保存</button></form>`}
function rows(list,fn){return list.length?list.map(x=>`<div class="ml-row"><div>${fn(x)}</div>${['task','pack'].includes(x.type)?`<button data-toggle="${x.id}" aria-label="${x.done?'取消完成':'标为完成'}">${x.done?'✓':'○'}</button>`:''}<button data-delete="${x.id}" aria-label="删除${esc(x.title)}">×</button></div>`).join(''):'<div class="ml-empty">这里还没有记录，添加你的第一条。</div>'}
function timerLeft(){const t=state.timer;if(!t)return 1500;return t.end?Math.max(0,Math.ceil((t.end-Date.now())/1000)):t.left}
function clock(){const n=timerLeft(),e=host?.querySelector('#mlClock');if(e)e.textContent=String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');if(state.timer?.end&&n===0){record('focus',state.timer.duration/60);state.timer=null;save();render();feedback('冲刺完成，已记录真实专注时长。')}}
function body(){
 switch(active){
 case'focus':return `<p>计时结束后才记录专注时长。刷新或切换工具不会重置正在运行的计时。</p><div class="ml-clock" id="mlClock" role="timer"></div><form class="ml-form" data-form="focus"><label>冲刺分钟<input name="minutes" type="number" min="1" max="180" value="25" required></label><button>${state.timer?.end?'暂停冲刺':state.timer?'继续冲刺':'开始冲刺'}</button><button type="button" data-reset>重置</button></form>`;
 case'task':return `<p>把下一步写清楚。点击圆圈完成，完成数按真实操作统计。</p>${form('task',[['title','要完成的任务'],['date','截止日期','date',day()],['priority','优先级（1 高 / 2 中 / 3 低）','number','2']])}${rows(items('task').sort((a,b)=>a.done-b.done||a.priority-b.priority||a.date.localeCompare(b.date)),x=>`<b>${x.done?'✓ ':''}${esc(x.title)}</b><small>优先级 ${x.priority} · ${esc(x.date)}</small>`)}`;
 case'card':return `<p>将问题和答案做成晶片。复习时先回想，再打开答案。</p>${form('card',[['title','问题'],['answer','答案']])}${rows(items('card'),x=>`<b>${esc(x.title)}</b><small>下次复习 ${esc(x.date)} · 已掌握 ${x.level||0} 轮</small>`)}`;
 case'exam':return `${form('exam',[['title','考试或重要事项'],['date','日期','date',day()]])}${rows(items('exam').sort((a,b)=>a.date.localeCompare(b.date)),x=>`<b>${esc(x.title)}</b><small>${diff(x.date)<0?'已过去 '+(-diff(x.date))+' 天':'还有 '+diff(x.date)+' 天'} · ${esc(x.date)}</small>`)}`;
 case'review':{const c=items('card').find(x=>x.date<=day());return `<p>根据晶片的实际复习日期生成，不填充示例。</p>${c?`<div class="ml-answer">${esc(c.title)}</div>${answer?`<div class="ml-answer">${esc(c.answer)}</div><button class="ml-action" data-rate="${c.id}" data-ok="0">还不熟，明天再看</button> <button class="ml-action" data-rate="${c.id}" data-ok="1">掌握，间隔复习</button>`:'<button class="ml-action" data-answer>查看答案</button>'}`:'<div class="ml-empty">今天没有到期晶片。可以先去「记忆晶片」添加。</div>'}`}
 case'expense':{const total=items('expense').filter(x=>x.date.slice(0,7)===day().slice(0,7)).reduce((a,x)=>a+x.amount,0);return `<p>本月已支出 ¥${total.toFixed(2)}${state.budget?' · 预算余额 ¥'+(state.budget-total).toFixed(2):''}</p>${form('budget',[['amount','月预算（元）','number',state.budget||'']])}${form('expense',[['title','支出用途'],['amount','金额（元）','number'],['date','消费日期','date',day()]])}${rows(items('expense').slice().reverse(),x=>`<b>${esc(x.title)} · ¥${Number(x.amount).toFixed(2)}</b><small>${esc(x.date)}</small>`)}`}
 case'course':return `<p>录入每周固定课程，按星期和时间排序。</p>${form('course',[['title','课程名称'],['weekday','星期（1 到 7）','number','1'],['time','上课时间','time','08:00'],['place','教室或地点']])}${rows(items('course').sort((a,b)=>a.weekday-b.weekday||a.time.localeCompare(b.time)),x=>`<b>${esc(x.title)}</b><small>周${'一二三四五六日'[x.weekday-1]} ${esc(x.time)} · ${esc(x.place)}</small>`)}`;
 case'diary':return `<p>为自己留一段记录。保存在当前设备，可导出备份。</p>${form('diary',[['date','记录日期','date',day()],['mood','此刻心情'],['title','今天发生了什么']])}${rows(items('diary').slice().reverse(),x=>`<b>${esc(x.title)}</b><small>${esc(x.date)} · ${esc(x.mood)}</small>`)}`;
 case'pack':return `${form('pack',[['title','出门要带的东西']])}<button class="ml-action" data-pack-reset>重置检查状态</button>${rows(items('pack'),x=>`<b>${x.done?'✓ ':''}${esc(x.title)}</b>`)}`;
 case'stats':{const f=state.logs.filter(x=>x.kind==='focus').reduce((a,x)=>a+x.n,0),done=items('task').filter(x=>x.done).length;const days=Array.from({length:7},(_,i)=>dateAfter(day(),i-6));const nums=days.map(d=>state.logs.filter(x=>x.day===d).length);const max=Math.max(1,...nums);return `<p>只统计实际使用记录。删除任务后，当前完成数量会同步减少。</p><div class="ml-stats"><div class="ml-stat"><b>${done}</b><span>当前已完成任务</span></div><div class="ml-stat"><b>${f}</b><span>累计专注分钟</span></div><div class="ml-stat"><b>${state.logs.filter(x=>x.kind==='review').length}</b><span>复习次数</span></div></div><div class="ml-bars">${days.map((d,i)=>`<div><i style="height:${nums[i]/max*90+2}px"></i>${d.slice(5)}<br>${nums[i]} 次</div>`).join('')}</div>`}
 }
}
function render(){if(!host?.isConnected)return;const t=tools.find(x=>x[0]===active);host.innerHTML=`<section class="meta-lab"><div class="ml-head"><div><h3>捞捞 · 星际学习实验室</h3><p>十个工具，把现实校园生活安排好。</p></div><span class="ml-status">本地数据 · 随时可备份</span></div><div class="ml-grid" role="tablist" aria-label="元宇宙实用工具">${tools.map((x,i)=>`<button class="ml-tool" role="tab" aria-selected="${x[0]===active}" aria-controls="mlPanel" data-tool="${x[0]}"><i>${String(i+1).padStart(2,'0')} / 模组</i><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div><div class="ml-panel" id="mlPanel" role="tabpanel" aria-label="${t[1]}"><h4>${t[1]}</h4>${body()}<div class="ml-feedback" role="status"></div></div><div class="ml-tip">此实验室使用独立本地记录，尚未与班级云端或原有工具同步。<button class="ml-action" data-export>导出备份</button> <label class="ml-action">导入备份<input type="file" accept="application/json,.json" data-import hidden></label></div></section>`;clock()}
function add(data){state.items.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),...data});record('create');render()}
function click(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.tool){active=b.dataset.tool;answer=false;render();return}if(b.dataset.toggle){const x=state.items.find(x=>x.id===b.dataset.toggle);x.done=!x.done;if(x.type==='task'&&x.done)record('task');save();render()}if(b.dataset.delete){if(!confirm('删除这条记录？'))return;state.items=state.items.filter(x=>x.id!==b.dataset.delete);save();render()}if(b.hasAttribute('data-answer')){answer=true;render()}if(b.dataset.rate){const x=state.items.find(x=>x.id===b.dataset.rate),ok=b.dataset.ok==='1';x.level=ok?Math.min(5,(x.level||0)+1):0;x.date=dateAfter(day(),ok?[1,3,7,14,30,60][x.level]:1);record('review');answer=false;render()}if(b.hasAttribute('data-reset')){state.timer=null;save();render()}if(b.hasAttribute('data-pack-reset')){items('pack').forEach(x=>x.done=false);save();render()}if(b.hasAttribute('data-export')){const url=URL.createObjectURL(new Blob([JSON.stringify({schema:1,...state},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='捞捞元宇宙-'+day()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
function submit(e){const t=e.target.dataset.form;if(!t)return;e.preventDefault();const d=Object.fromEntries(new FormData(e.target));for(const k in d)d[k]=d[k].trim();if(Object.values(d).some(x=>!x)){feedback('请填写完整。');return}if(t==='focus'){if(state.timer?.end)state.timer={duration:state.timer.duration,left:timerLeft()};else{const n=state.timer?state.timer.left:Number(d.minutes)*60;if(!Number.isFinite(n)||n<1||n>10800){feedback('请输入 1 到 180 分钟。');return}state.timer={duration:state.timer?.duration||n,end:Date.now()+n*1000,left:n}}save();render();return}if(['expense','budget'].includes(t)){d.amount=Number(d.amount);if(!Number.isFinite(d.amount)||d.amount<=0){feedback('金额必须大于 0。');return}}if(t==='budget'){state.budget=d.amount;save();render();return}if(t==='course'){d.weekday=Number(d.weekday);if(!Number.isInteger(d.weekday)||d.weekday<1||d.weekday>7){feedback('星期请输入 1 到 7。');return}}if(t==='task'){d.priority=Number(d.priority);if(!Number.isInteger(d.priority)||d.priority<1||d.priority>3){feedback('优先级请输入 1 到 3。');return}}if(t==='card'){d.date=day();d.level=0}add({type:t,done:false,...d})}
async function importFile(e){if(!e.target.matches('[data-import]')||!e.target.files[0])return;try{const file=e.target.files[0];if(file.size>2e6)throw Error();const x=JSON.parse(await file.text());if(x.schema!==1||!Array.isArray(x.items)||!Array.isArray(x.logs)||x.items.length>5000||x.logs.length>20000)throw Error();const dateValid=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&new Date(s+'T12:00:00').toLocaleDateString('sv-SE')===s;
const kinds=tools.map(t=>t[0]),ids=new Set();
for(const t of x.items){
 if(!t||!kinds.includes(t.type)||typeof t.id!=='string'||!/^[a-zA-Z0-9_-]{1,80}$/.test(t.id)||ids.has(t.id)||typeof t.title!=='string'||!t.title.trim()||t.title.length>1000)throw Error();ids.add(t.id);
 if(['task','exam','expense','diary','card'].includes(t.type)&&!dateValid(t.date))throw Error();
 if(t.type==='task'&&(!Number.isInteger(t.priority)||t.priority<1||t.priority>3))throw Error();
 if(t.type==='course'&&(!Number.isInteger(t.weekday)||t.weekday<1||t.weekday>7||!/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test(t.time)||typeof t.place!=='string'))throw Error();
 if(t.type==='expense'&&(!Number.isFinite(t.amount)||t.amount<=0))throw Error();
 if(t.type==='card'&&(typeof t.answer!=='string'||!t.answer.trim()||!Number.isInteger(t.level)||t.level<0||t.level>5))throw Error();
}
if(x.logs.some(t=>!t||!dateValid(t.day)||!Number.isFinite(t.n)||t.n<0||typeof t.kind!=='string')||!Number.isFinite(x.budget)||x.budget<0)throw Error();
if(!confirm('导入会替换此实验室的当前记录，是否继续？'))return;state={items:x.items,logs:x.logs,budget:Number.isFinite(x.budget)?x.budget:0,timer:null};if(save())render()}catch(err){feedback('备份格式不正确，当前数据保持原样。')}}
window.MetaLab={mount(el){if(!el)return;host=el;host.addEventListener('click',click);host.addEventListener('submit',submit);host.addEventListener('change',importFile);render();if(!tick)tick=setInterval(clock,1000)}};
})();
